# workflow triggers
on:
  workflow_dispatch:
  # Allows external webhook trigger
  repository_dispatch:
    types: [webhook]
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x ../../hello.sh
         ../../hello.sh
      shell: bash
